name: prefix

on:
  push:
    paths:
      - .github/workflows/prefix.yml

jobs:
  prefix-symbols:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          # - target: x86_64-unknown-linux-gnu
          #   os: ubuntu-latest
          #   build: cargo build --target
          #   test: true
          #   custom_env: {}
          # - target: aarch64-unknown-linux-gnu
          #   os: ubuntu-latest
          #   build: cargo build --target
          #   test: false
          #   apt_packages: crossbuild-essential-arm64 binutils-multiarch
          #   custom_env:
          #     CC_aarch64_unknown_linux_gnu: aarch64-linux-gnu-gcc
          #     CXX_aarch64_unknown_linux_gnu: aarch64-linux-gnu-g++
          #     CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER: aarch64-linux-gnu-g++
          # - target: armv7-linux-androideabi
          #   os: ubuntu-latest
          #   build: cargo ndk build --target
          #   test: false
          #   custom_env: {}
          # - target: aarch64-linux-android
          #   os: ubuntu-latest
          #   build: cargo ndk build --target
          #   test: false
          #   custom_env: {}
          # - target: x86_64-linux-android
          #   os: ubuntu-latest
          #   build: cargo ndk build --target
          #   test: false
          #   custom_env: {}
          # Openssl issue on i686: https://github.com/rust-openssl/rust-openssl/issues/2163#issuecomment-2692363343
          # - target: i686-linux-android
          #   os: ubuntu-latest
          #   build: cargo ndk build --target
          #   test: false
          #   custom_env: {}
          - target: aarch64-apple-darwin
            os: macos-latest
            build: cargo build --target
            test: true
            custom_env: {}
          # - target: x86_64-apple-darwin
          #   os: macos-latest
          #   build: cargo build --target
          #   test: false
          #   custom_env: {}
          # - target: aarch64-apple-ios
          #   os: macos-latest
          #   build: cargo build --target
          #   test: false
          #   custom_env:
          #     IPHONEOS_DEPLOYMENT_TARGET: 26.1
    defaults:
      run:
        working-directory: .github/prefix-test/
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: brew
        run: |
          brew install binutils
          brew info binutils
          echo -----------------------------------------------------------------------
          echo "PATH=/opt/homebrew/opt/binutils/bin:$PATH" >> $GITHUB_ENV
          objcopy
          echo END
          exit 9
      - name: Install Rust toolchain
        run: rustup target add ${{ matrix.target }}
      - name: Install target-specific APT dependencies
        if: matrix.apt_packages != ''
        run: sudo apt update && sudo apt install -y ${{ matrix.apt_packages }}
      - name: Install cargo-ndk
        if: contains(matrix.target, 'android')
        run: cargo install cargo-ndk
      - name: Build without prefixing
        if: ${{ !contains(matrix.target, 'apple') }}
        env: ${{ matrix.custom_env }}
        run: |
          RC=0
          ${{ matrix.build }} ${{ matrix.target }} >logs 2>&1 || RC=$?
          if [[ $RC == 0 || (! $(cat logs | grep "lld: error: duplicate symbol") && ! $(cat logs | grep "multiple definition of")) ]]; then
            cat logs
            echo "Build finished without duplicate symbols: $RC"
            exit 1
          fi
          cat logs
          echo "Failed as expected: $RC"
      - name: Apple works without prefixing
        if: contains(matrix.target, 'apple')
        env: ${{ matrix.custom_env }}
        run: ${{ matrix.build }} ${{ matrix.target }}
      - name: Add prefix-symbols feature
        run: cargo add boring-sys2 --path ../../boring-sys/ -F prefix-symbols
      - name: Build with prefixing
        env: ${{ matrix.custom_env }}
        run: ${{ matrix.build }} ${{ matrix.target }}
      - name: Check that wreq is working
        if: matrix.test == true
        run: |
          binary=$(find target -type f -name prefix-test -print -quit)
          echo "$binary"
          "./$binary"
