name: prefix

on:
  push:
    paths:
      - .github/workflows/prefix.yml

jobs:
  prefix-symbols:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Create test project
        run: |
          cargo init brssl2-prefix
          cd brssl2-prefix
          cargo add boring-sys2 --path ../boring-sys/
          cargo add openssl-sys -F vendored
          echo "fn main() {boring_sys2::init(); openssl_sys::init();}" > src/main.rs
      - name: Build without prefixing (should fail)
        run: |
          if ! cargo build 2>&1 | grep "rust-lld: error: duplicate symbol"; then
            echo "Build without prefixing succeeded, should fail.";
            exit 1;
          fi
      - name: Build with prefixing (should not fail)
        run: |
          pwd
          cargo add boring-sys2 --path ../boring-sys/ -F prefix-symbols
          cargo build
